'use strict';
const $ = (s, el = document) => el.querySelector(s);
const esc = value => String(value ?? '').replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const icon = name => `<svg aria-hidden="true"><use href="#i-${name}"/></svg>`;
const norm = s => String(s ?? '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();
const state = {data:null,page:'overview',caseTab:'results',caseSearch:'',layer:'',status:'',group:'',criterion:'',casePage:1,evidenceTab:'groups',evidenceSearch:'',evidenceGroup:'',evidencePage:1,docPath:'README.md',source:false,imagePaths:[],imageIndex:0,imageScope:null,imageZoom:100,imageFit:true,activeCase:null,detailTab:'result',comparisonIndex:0};
const pageTitles = {overview:'Visão geral',cases:'Cenários e resultados',automation:'Automação',evidence:'Evidências',bugs:'Bugs',documents:'Documentos'};
Object.assign(state,{automationSearch:'',automationLayer:'',automationStatus:'',activeAutomation:null,automationTab:'result'});
const automationPayloads = new Map();
const groupTitles = {'CT-001':'Cupom: desconto de 10%','CT-002':'Cupom: letras e espaços','CT-003':'Cupom inválido','CT-004':'Cupom expirado','CT-005':'Remover e reaplicar cupom','CT-006':'Frete no limite de R$ 200,00','CT-007':'Frete acima de R$ 200,00','CT-008':'Frete abaixo de R$ 200,00','CT-009':'Quantidade máxima por produto','CT-010':'Recalcular o carrinho','CT-011':'Precisão monetária','CT-012':'Pedido válido','CT-013':'Dados inválidos do cliente','CT-014':'Consulta de produtos','CT-015':'Validação de itens','CT-016':'Erros de protocolo'};
const fileURL = path => './files/' + String(path).split('/').map(encodeURIComponent).join('/');
const stripMD = value => String(value ?? '').replace(/\[([^\]]+)\]\([^)]+\)/g,'$1').replace(/[*`]/g,'').replace(/<[^>]*>/g,'');
const badge = (text, type = 'gray') => `<span class="badge ${type}"><span class="status-dot"></span>${esc(text)}</span>`;
const statusBadge = value => badge(value, value === 'Aprovado' ? 'green' : value === 'Reprovado' ? 'red' : 'amber');
const docTitle = d => d.path.endsWith('.feature') ? 'Gherkin · ' + ({carrinho:'Carrinho',checkout:'Checkout',api:'API'}[d.path.split('/').pop().replace('.feature','')] || d.path.split('/').pop()) : d.title;
const rawStatus = r => String(r.status ?? r.resultado ?? '');
const groupOf = id => String(id).match(/CT-\d{3}/)?.[0] ?? '';
const heading = (title,desc='',right='') => `<div class="page-heading"><div><h1>${esc(title)}</h1>${desc?`<p>${esc(desc)}</p>`:''}</div>${right?`<div class="right">${right}</div>`:''}</div>`;
const empty = (title='Nenhum resultado encontrado',text='Ajuste a busca ou os filtros para ver outros registros.') => `<div class="empty-state"><h2>${esc(title)}</h2><p>${esc(text)}</p></div>`;
const dateText = value => value && /^\d{4}-\d{2}-\d{2}T/.test(value) ? new Date(value).toLocaleString('pt-BR',{timeZone:'America/New_York',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit',second:'2-digit'})+' · UTC−04:00' : value || 'Horário não registrado';
function toast(message){const box=$('#toast');box.textContent=message;box.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>box.classList.remove('show'),3000);}
function dataCases(){return state.data.cases || [];}
function caseDescription(c){return c.description||groupById(c.group||groupOf(c.id))?.objective||'';}
function groupById(id){return state.data.groups.find(g=>g.id===id);}
function evidenceById(id){return state.data.evidenceGroups.find(g=>g.id===id);}
function docByPath(path){return state.data.documents.find(d=>d.path===path);}
function captures(){return state.data.captures || [];}
function caseCriteria(c){return groupById(c.group||groupOf(c.id))?.criteria||[];}
function criteriaArray(value){return Array.isArray(value)?value:String(value||'').match(/CA\d{2}/g)||[];}
function caseBugs(c){return c.bugIds||String(c.actual||'').match(/BUG-\d{3}/g)||[];}
function casesFiltered(){return dataCases().filter(c=>(!state.layer||c.layer===state.layer)&&(!state.status||rawStatus(c)===state.status)&&(!state.group||(c.group||groupOf(c.id))===state.group)&&(!state.criterion||criteriaArray(caseCriteria(c)).includes(state.criterion))&&(!state.caseSearch||norm([c.id,caseDescription(c),c.input,c.expected,c.actual,groupById(c.group||groupOf(c.id))?.objective,...caseBugs(c)].join(' ')).includes(norm(state.caseSearch))));}
function bugRows(){return state.data.bugs.map(b=>{const related=dataCases().filter(c=>caseBugs(c).includes(b.id));return `<button class="bug-row" data-bug="${esc(b.id)}" aria-label="Abrir ${esc(b.id)}: ${esc(b.title)}"><code>${esc(b.id)}</code><span class="bug-row-copy"><strong>${esc(b.title)}</strong><small>${related.length} casos afetados</small></span>${badge('Severidade '+(b.severity||'—'),b.severity==='Alta'?'red':'amber')}<span class="bug-row-open">Ver bug ${icon('arrow')}</span></button>`;}).join('');}
function overview(){
 const s=state.data.summary,a=s.automation,percent=s.totalCases?Math.round(s.passed/s.totalCases*100):0;
 const automationFoot=a.executed?[a.passed+' aprovados',a.knownFailures+' falhas conhecidas',...(a.unexpectedFailures?[a.unexpectedFailures+' falhas inesperadas']:[]),...(a.skipped?[a.skipped+' ignorados']:[])].join(' · '):'Execução não comprovada · mínimo de '+a.required;
 const layer=(name,l)=>`<div class="layer-row"><div class="layer-title"><strong>${esc(name)}</strong><span class="muted">${l.total} casos</span></div><div class="stack" aria-label="${l.passed} aprovados e ${l.failed} reprovados"><span class="pass" style="width:${l.passed/l.total*100}%"></span><span class="fail" style="width:${l.failed/l.total*100}%"></span></div><div class="layer-footer"><span>${l.passed} aprovados</span><span>${l.failed} reprovados</span></div></div>`;
 return heading('Visão do projeto')+`<section class="metrics" aria-label="Resumo do projeto">
 <article class="metric"><div class="metric-icon">${icon('list')}</div><div class="metric-label">Casos executados</div><strong class="metric-value">${s.totalCases}</strong><div class="metric-foot">${state.data.groups.length} grupos · ${s.definitionCount} definições Gherkin</div></article>
 <article class="metric"><div class="metric-icon">${icon('check')}</div><div class="metric-label">Taxa de aprovação</div><strong class="metric-value">${percent}<span style="font-size:21px">%</span></strong><div class="metric-foot"><strong>${s.passed} aprovados</strong> · ${s.failed} reprovados</div></article>
 <article class="metric"><div class="metric-icon">${icon('bug')}</div><div class="metric-label">Bugs confirmados</div><strong class="metric-value">${s.bugCount}</strong></article>
 <article class="metric"><div class="metric-icon">${icon('code')}</div><div class="metric-label">Automação Playwright</div><strong class="metric-value small">${a.executed?a.total+' executados':'Não comprovada'}</strong><div class="metric-foot">${esc(automationFoot)}</div><button class="text-button" data-page="automation">Ver testes ${icon('arrow')}</button></article></section>
 <div class="grid-two"><section class="card"><div class="card-heading"><h2>Resultado da execução</h2><button class="text-button" data-page="cases">Ver cenários ${icon('arrow')}</button></div><div class="distribution"><div class="donut" style="--pass-angle:${percent*3.6}deg" aria-label="${percent}% dos casos aprovados"><div class="donut-label"><strong>${s.totalCases}</strong><span>casos executados</span></div></div><div class="legend"><div class="legend-row"><i style="background:var(--green)"></i>Aprovados<strong>${s.passed}</strong></div><div class="legend-row"><i style="background:#eab0b7"></i>Reprovados<strong>${s.failed}</strong></div><div class="legend-row"><i style="background:#dae2ed"></i>Bloqueados<strong>0</strong></div></div></div></section>
 <section class="card"><div class="card-heading"><h2>Execução por camada</h2></div>${layer('Interface · UI',s.ui)}${layer('API',s.api)}</section></div>
 <div class="section-heading"><h2>Bugs encontrados</h2><button class="text-button" data-failed>Ver ${s.failed} reprovações ${icon('arrow')}</button></div><section class="bug-list">${bugRows()}</section>
 <div style="margin-top:23px">
 <section class="card"><div class="card-heading"><h2>Evidências e exploração</h2></div><div style="display:flex;align-items:baseline;gap:9px"><strong style="font-size:29px;font-weight:650;letter-spacing:-1px">${s.captureCount}</strong><span class="muted" style="font-size:11px">capturas no projeto</span></div><p class="muted" style="font-size:11px;margin:5px 0 15px">${s.currentCaptureCount} capturas de 07/10 + ${s.captureCount-s.currentCaptureCount} anteriores.</p><button class="button compact" data-page="evidence">${icon('image')}Explorar evidências</button><div class="explore-callout"><div><strong>EXP-01 · 1 min 41 s</strong><span>Limpeza, abas e recuperação do checkout. Sem novos bugs.</span></div><button class="icon-button" data-evidence="EV-036" aria-label="Ver sessão exploratória">${icon('arrow')}</button></div></section></div>`;
}
function selectOptions(values,current){return values.map(([value,label])=>`<option value="${esc(value)}" ${value===current?'selected':''}>${esc(label)}</option>`).join('');}
const automationLabels={passed:'Aprovado',known_failure:'Falha conhecida',unexpected_failure:'Falha inesperada',skipped:'Não executado'};
function automatedTests(){return state.data.automation?.tests||[];}
function automatedTest(id){return automatedTests().find(t=>t.id===id);}
function automationBadge(status){return badge(automationLabels[status]||status,status==='passed'?'green':status==='skipped'?'amber':'red');}
function durationText(ms){return Number.isFinite(ms)?(ms/1000).toLocaleString('pt-BR',{maximumFractionDigits:1})+' s':'—';}
function automationFiltered(){return automatedTests().filter(t=>(!state.automationLayer||t.layer===state.automationLayer)&&(!state.automationStatus||t.status===state.automationStatus)&&(!state.automationSearch||norm([t.id,t.objective,t.title,...t.ctIds,...t.bugIds].join(' ')).includes(norm(state.automationSearch))));}
function automationTable(){
 const tests=automationFiltered();
 return tests.length?`<div class="table-wrap"><table class="results-table automation-table"><thead><tr><th>Teste automatizado</th><th>Camada</th><th>Resultado</th><th>Duração</th><th>Detalhe</th></tr></thead><tbody>${tests.map(t=>`<tr class="row-link" data-automation="${esc(t.id)}" tabindex="0" role="button" aria-label="Ver ${esc(t.id)}"><td><span class="case-name">${esc(t.id)}</span><span class="case-objective">${esc(t.objective)}</span><span class="case-desc">${esc(t.ctIds.join(' · '))}</span></td><td>${badge(t.layer,'blue')}</td><td>${automationBadge(t.status)}${t.bugIds.map(id=>`<span class="case-desc automation-bug-id">${esc(id)}</span>`).join('')}</td><td class="automation-duration">${esc(durationText(t.durationMs))}</td><td>${icon('arrow')}</td></tr>`).join('')}</tbody></table></div>`:empty();
}
function updateAutomationResults(){const count=$('#automation-count'),table=$('#automation-results');if(count)count.textContent=`${automationFiltered().length} de ${automatedTests().length} testes`;if(table)table.innerHTML=automationTable();}
function automationPage(){
 const a=state.data.automation,s=a?.summary,environment=a?.environment||{};
 if(!a?.executed)return heading('Testes automatizados')+empty('Execução não registrada','Consulte os arquivos de automação em Documentos.');
 const summary=[[s.total,'Executados',''],[s.passed,'Aprovados','green'],[s.knownFailures,'Falhas conhecidas','red'],[s.unexpectedFailures,'Falhas inesperadas',s.unexpectedFailures?'red':'']];
 return heading('Testes automatizados',dateText(a.startedAt)+' · '+durationText(a.durationMs),`<button class="button compact" data-doc="README.md" data-anchor="executar-a-automação">${icon('file')}Como executar</button>`)+`<div class="automation-summary" aria-label="Resumo da automação">${summary.map(([n,label,color])=>`<div><strong class="${color}">${n}</strong><span>${label}</span></div>`).join('')}${s.skipped?`<div><strong>${s.skipped}</strong><span>Não executados</span></div>`:''}</div><div class="toolbar"><label class="search-field">${icon('search')}<input id="automation-search" aria-label="Buscar teste automatizado" type="search" placeholder="Buscar teste, CT ou bug…" value="${esc(state.automationSearch)}"></label><select id="automation-layer" aria-label="Filtrar camada da automação">${selectOptions([['','Todas as camadas'],['UI','Interface · UI'],['API','API']],state.automationLayer)}</select><select id="automation-status" aria-label="Filtrar resultado da automação">${selectOptions([['','Todos os resultados'],...Object.entries(automationLabels)],state.automationStatus)}</select><button class="text-button" data-automation-clear>Limpar</button></div><div class="table-count"><span id="automation-count">${automationFiltered().length} de ${automatedTests().length} testes</span></div><div id="automation-results">${automationTable()}</div><details class="automation-run-details"><summary>Ambiente e registro da execução</summary><dl>${[['Navegador','Chromium '+(environment.chromium||'—')],['Playwright',environment.playwright||'—'],['Node.js',environment.node||'—'],['Sistema',environment.os||'—'],['Ambiente',environment.baseURL||'—']].map(([name,value])=>`<div><dt>${esc(name)}</dt><dd>${esc(value)}</dd></div>`).join('')}</dl><button class="text-button" data-doc="${esc(a.recordPath)}">Registro completo ${icon('arrow')}</button></details>`;
}
function highlightedCode(source,path){
 const value=String(source??''),language=/\.tsx?$/i.test(path)?'typescript':/\.json$/i.test(path)?'json':/\.[cm]?js$/i.test(path)?'javascript':null;
 const grammar=language&&window.Prism?.languages?.[language];
 return grammar?window.Prism.highlight(value,grammar,language):esc(value);
}
function automationCodeBlock(path){
 const doc=docByPath(path);
 if(!doc)return `<p class="muted">${esc(path)} · arquivo não localizado.</p>`;
 return `<details class="automation-code-block"><summary>${icon('code')}<span>${esc(path)}</span></summary><pre class="source" tabindex="0" role="region" aria-label="Código de ${esc(path)}"><code class="syntax-code">${highlightedCode(doc.content||'(Arquivo vazio)',path)}</code></pre></details>`;
}
function automationFilesHTML(t){
 const specs=t.sourcePaths||[],pages=t.layer==='UI'?state.data.documents.filter(d=>d.path.startsWith('tests/pages/')):[];
 const api=t.layer==='API'?['tests/api/LojaApi.ts','tests/api/dados.ts','tests/api/validacoes.ts']:[];
 return `<div class="automation-code-sections"><section><h3>Especificação</h3>${specs.map(automationCodeBlock).join('')||'<p class="muted">Arquivo não localizado.</p>'}</section>${pages.length?`<section><h3>Page Objects e componente</h3>${pages.map(d=>automationCodeBlock(d.path)).join('')}</section>`:''}${api.length?`<section><h3>Cliente da API e apoio</h3>${api.map(automationCodeBlock).join('')}</section>`:''}<section><h3>Configuração e evidências</h3>${['playwright.config.ts','tests/helpers.ts'].map(automationCodeBlock).join('')}</section></div>`;
}
function automationStepLine(step){return String(step.snippet||'').split('\n').find(s=>Number(s.match(/^\s*(\d+)\s*\|/)?.[1])===step.location?.line)||'';}
function automationCheckLabel(step){
 const fields={subtotal:'Subtotal',desconto:'Desconto',frete:'Frete',total:'Total'},target=String(step.subtitle||''),line=automationStepLine(step);
 if(['Status HTTP','Código de erro','Campo com erro','Mensagem de erro','Ausência de pedido criado','Formato JSON da resposta'].includes(step.title))return step.title;
 const field=target.match(/data-valor="(subtotal|desconto|frete|total)"/)?.[1]||(/^subtotal$|^desconto$|^frete$|^total$/.test(step.title)?step.title:null);
 if(field)return fields[field];
 if(step.title.startsWith('Frete no subtotal'))return 'Frete';
 if(step.title.startsWith('Total no subtotal'))return 'Total';
 if(target.includes('#titulo-vitrine'))return 'Catálogo';
 if(target.includes('Carrinho 0 itens'))return 'Carrinho vazio';
 if(target.includes("name: 'Carrinho'"))return 'Tela do carrinho';
 if(target.includes("name: 'Finalizar compra'"))return 'Tela do checkout';
 if(target.includes('#campo-cupom'))return 'Campo do cupom';
 if(target.includes('Remover cupom'))return 'Botão de remover cupom';
 if(target.includes('Faltam R'))return 'Aviso de frete';
 if(target.includes('Cupom inválido')||target.includes('Cupom expirado'))return 'Rejeição do cupom';
 if(target.includes('#campo-cep-erro'))return 'Validação do CEP';
 if(target.includes('Limite de 5 unidades'))return 'Aviso do limite de unidades';
 if(target.includes('Aumentar quantidade'))return 'Botão de aumentar quantidade';
 if(target.includes("locator('output')"))return 'Quantidade do produto';
 if(line.includes('resposta.status()')||line.includes('resultado.statusHTTP'))return 'Status HTTP';
 if(line.includes("headers()['content-type']"))return 'Formato JSON da resposta';
 if(line.includes('dados.erro?.codigo'))return 'Código de erro';
 if(line.includes('dados.erro?.campo'))return 'Campo com erro';
 if(line.includes('dados.erro?.mensagem'))return 'Mensagem de erro';
 if(line.includes('dados.numero'))return 'Ausência de pedido criado';
 if(line.includes('pedido.cliente.cep'))return 'CEP do pedido';
 if(line.includes('pedido.cliente'))return 'Dados do cliente';
 if(line.includes('pedido.numero')&&!line.includes('confirmado.titulo'))return 'Número do pedido';
 if(line.includes('pedido.cupom'))return 'Cupom do pedido';
 if(line.includes('pedido.criadoEm'))return 'Data de criação do pedido';
 if(line.includes('expect(pedido)'))return 'Valores do pedido na API';
 if(line.includes('confirmado.titulo'))return 'Confirmação do pedido';
 if(line.includes('toHaveURL'))return line.includes('pedido-confirmado')?'Página de confirmação':'Página do checkout';
 if(line.includes('expect(aviso)'))return 'Aviso de frete';
 return automationCheckKind(step);
}
function automationCheckKind(step){
 const method=String(step.title).match(/to[A-Z]\w+/)?.[0]||String(step.snippet||'').match(/\.(to[A-Z]\w+)\(/)?.[1];
 return ({toBeVisible:'Visibilidade',toHaveText:'Texto',toHaveCount:'Quantidade de elementos',toBeDisabled:'Botão desabilitado',toBeEnabled:'Botão habilitado',toHaveURL:'Endereço da página',toMatchObject:'Dados esperados',toContain:'Conteúdo esperado',toBeUndefined:'Valor ausente',toMatch:'Formato esperado',toBe:'Valor esperado'})[method]||'Verificação';
}
function automationChecksHTML(t){
 const flat=[];
 function visit(steps,preparation=false){for(const step of steps||[]){const before=preparation||step.title==='Before Hooks';flat.push({...step,preparation:before});visit(step.steps,before);}}
 visit(t.steps);
 const checks=[],groups=[],preparation=[],pending=[];
 const images=t.attachments.filter(f=>f.type==='image');
 for(const step of flat){
  const isCheck=/^Expect\b/.test(step.title)||['subtotal','desconto','frete','total'].includes(step.title)||/\bexpect(?:\.soft)?\(/.test(automationStepLine(step));
  if(isCheck){const check={...step,label:automationCheckLabel(step),status:step.skipped?'skipped':step.error?'failed':'passed'};checks.push(check);(step.preparation?preparation:pending).push(check);}
  if(/^Attach\b/.test(step.title)){const attachment=images.find(f=>step.title.includes(f.path.split('/').pop().replace(/\.png$/i,'')));if(attachment&&pending.length)groups.push({label:attachment.stage.replace(/^\d+\.\s*/,''),checks:pending.splice(0)});}
 }
 if(preparation.length)groups.unshift({label:'Preparação',checks:preparation});
 if(pending.length)groups.push({label:t.layer==='API'?'Validações da API':'Validações finais',checks:pending});
 if(!checks.length)return '<p class="automation-checks-unavailable">Verificações detalhadas indisponíveis para esta execução.</p>';
 const counts={passed:0,failed:0,skipped:0};for(const c of checks)counts[c.status]++;
 const items=groups.map(group=>{const failed=group.checks.filter(c=>c.status==='failed').length,skipped=group.checks.filter(c=>c.status==='skipped').length,subjects=[...new Set(group.checks.map(c=>c.label))];
  return `<details class="automation-check-group"><summary><span><strong>${esc(group.label)}</strong><small>${esc(subjects.join(' · '))}</small></span><span class="automation-check-count">${group.checks.length} verificações</span>${badge(failed?failed+' '+(failed===1?'falha':'falhas'):skipped?skipped+' não executadas':'Aprovado',failed?'red':skipped?'amber':'green')}</summary><ul>${group.checks.map(c=>`<li><span>${esc(c.label)}<small>${esc(automationCheckKind(c))} · ${esc(c.location?.file||'')}${c.location?.line?':'+c.location.line:''}</small></span>${badge(c.status==='passed'?'Aprovado':c.status==='failed'?'Falhou':'Não executado',c.status==='passed'?'green':c.status==='failed'?'red':'amber')}</li>`).join('')}</ul></details>`;
 }).join('');
 return `<section class="automation-checks"><div class="automation-checks-heading"><h3>Verificações executadas</h3><span>${counts.passed} aprovadas · ${counts.failed} falhas${counts.skipped?' · '+counts.skipped+' não executadas':''}</span></div>${items}</section>`;
}
function automationResultHTML(t){
 const labels={subtotal:'Subtotal',desconto:'Desconto',frete:'Frete',total:'Total'},comparisons=[];
 for(const error of t.errors){const field=error.match(/data-valor="(subtotal|desconto|frete|total)"/)?.[1]||error.match(/^Error:\s*(Frete|Total) no subtotal/m)?.[1]?.toLowerCase(),expected=error.match(/Expected:\s*"([^"]+)"/)?.[1],actual=error.match(/Received:\s*"([^"]+)"/)?.[1];if(field&&expected&&actual)comparisons.push([labels[field],expected,actual]);else if(error.includes('resposta.status()')||error.includes('resultado.statusHTTP')||/^Error:\s*Status HTTP/m.test(error)){const wanted=error.match(/Expected:\s*(\d+)/)?.[1],got=error.match(/Received:\s*(\d+)/)?.[1];if(wanted&&got)comparisons.push(['HTTP',wanted,got]);}}
 const comparison=comparisons.length?`<table class="money-table"><thead><tr><th>Verificação</th><th>Esperado</th><th>Obtido</th></tr></thead><tbody>${comparisons.map(([name,expected,actual])=>`<tr class="money-fail"><th>${esc(name)}</th><td>${esc(expected)}</td><td>${esc(actual)}</td></tr>`).join('')}</tbody></table>`:'';
 const errors=t.errors.length?`<details class="automation-errors"><summary>Falhas das asserções · ${t.errors.length}</summary>${t.errors.map(error=>`<pre class="source"><code>${esc(error)}</code></pre>`).join('')}</details>`:'';
 return `${comparison}${automationChecksHTML(t)}<section class="automation-coverage"><h3>Cenários cobertos</h3><div>${t.ctIds.map(id=>`<button class="button compact" data-automation-ct="${esc(id)}">${esc(id)} ${icon('arrow')}</button>`).join('')}</div></section>${errors}<a class="button compact" href="${fileURL(t.recordPath)}" download="${esc(t.id)}.json">${icon('file')}Registro deste teste</a>`;
}
function automationEvidenceHTML(t){
 const images=t.attachments.filter(f=>f.type==='image'),jsons=t.attachments.filter(f=>f.type==='json'),others=t.attachments.filter(f=>f.type!=='image'&&f.type!=='json');
 return `<div class="evidence-actions"><span>${images.length} ${images.length===1?'captura':'capturas'} · ${jsons.length} ${jsons.length===1?'registro':'registros'} de API</span><a class="button compact" href="${fileURL(t.recordPath)}" download="${esc(t.id)}.json">${icon('file')}Registro deste teste</a></div>${images.length?`<div class="case-evidence-grid ${images.length===1?'montage':''}">${images.slice(0,2).map(f=>caseImage(f.path,f.stage,t.id)).join('')}</div><div class="case-thumbnails">${images.map((f,i)=>`<button class="case-thumbnail" data-image="${esc(f.path)}" data-image-scope="${esc(t.id)}" aria-label="${esc(t.id)} · Etapa ${i+1}: ${esc(f.stage)}"><img loading="lazy" src="${fileURL(f.path)}" alt=""><span>${esc(f.stage)}</span></button>`).join('')}</div>`:''}${jsons.map((f,i)=>`<section class="automation-api-record"><div class="evidence-group-bar"><h3>${esc(f.stage)}</h3><a class="text-button" href="${fileURL(f.path)}" target="_blank" rel="noopener">JSON original ${icon('external')}</a></div><div id="automation-payload-${i}" role="status">Carregando registro de API…</div></section>`).join('')}${others.length?`<details class="automation-errors"><summary>Contexto da execução</summary><div class="automation-source-list">${others.map(f=>`<a class="button compact" href="${fileURL(f.path)}" target="_blank" rel="noopener">${icon('file')}${esc(f.label)}</a>`).join('')}</div></details>`:''}${!t.attachments.length?empty('Sem anexos registrados'):''}`;
}
async function loadAutomationPayloads(t){
 await Promise.all(t.attachments.filter(f=>f.type==='json').map(async(f,i)=>{
  let html;
  try{if(!automationPayloads.has(f.path)){const response=await fetch(fileURL(f.path),{cache:'no-store'});if(!response.ok)throw new Error();automationPayloads.set(f.path,await response.json());}const record=automationPayloads.get(f.path);html=`<div class="api-request-bar">${record.metodo?badge(record.metodo,'blue'):''}${record.rota?`<code>${esc(record.rota)}</code>`:''}${record.esperado?.statusHTTP?badge('Esperado HTTP '+record.esperado.statusHTTP,'gray'):''}${record.statusHTTP?badge('Obtido HTTP '+record.statusHTTP,t.status==='passed'?'green':'red'):''}</div><div class="api-payloads"><section><h3>Requisição</h3><pre class="source"><code>${esc(JSON.stringify(record.requisicao??record,null,2))}</code></pre></section><section><h3>Resposta</h3><pre class="source"><code>${esc(JSON.stringify(record.resposta??record,null,2))}</code></pre></section></div>`;}catch{html='<p class="muted">Não foi possível carregar o registro. Abra o JSON original.</p>';}
  if(state.activeAutomation===t.id&&state.automationTab==='evidence'&&$('#detail-dialog').open){const box=$('#automation-payload-'+i);if(box)box.innerHTML=html;}
 }));
}
function renderAutomationDetail(){
 const t=automatedTest(state.activeAutomation);if(!t)return;
 const tabs=[['result','Resultado'],['evidence','Evidências'],['code','Código']],content=state.automationTab==='evidence'?automationEvidenceHTML(t):state.automationTab==='code'?automationFilesHTML(t):automationResultHTML(t);
 modal(t.id,'Automação · Playwright',`<div class="case-summary-bar">${automationBadge(t.status)}${badge(t.layer,'blue')}<span>${esc(dateText(t.startedAt))} · ${esc(durationText(t.durationMs))}</span>${t.bugIds.length?`<div class="case-bug-actions">${t.bugIds.map(id=>`<button class="button case-bug-action" data-bug="${esc(id)}">${icon('bug')}Ver ${esc(id)} ${icon('arrow')}</button>`).join('')}</div>`:''}</div><section class="case-objective-block"><h3>Objetivo</h3><p>${esc(t.objective)}</p></section><div class="details-tabs" role="tablist" aria-label="Detalhes da automação">${tabs.map(([id,label])=>`<button class="detail-tab ${state.automationTab===id?'active':''}" role="tab" aria-selected="${state.automationTab===id}" data-automation-tab="${id}">${label}</button>`).join('')}</div><div class="case-context">${content}</div>`);
 if(state.automationTab==='evidence')loadAutomationPayloads(t);
}
function openAutomation(id){state.activeCase=null;state.activeAutomation=id;state.automationTab='result';renderAutomationDetail();}
function imagePackage(scope){if(/^AUTO-/.test(scope||'')){const t=automatedTest(scope);return t?{caseId:t.id,images:t.attachments.filter(f=>f.type==='image')}:null;}return casePackage(scope);}
function pagination(current,total,kind){if(total<=1)return '';let pages=[];for(let n=1;n<=total;n++)pages.push(`<button class="page-btn ${n===current?'active':''}" data-pagination="${kind}" data-number="${n}" aria-label="Página ${n}" ${n===current?'aria-current="page"':''}>${n}</button>`);return `<div class="pagination"><button class="page-btn" data-pagination="${kind}" data-number="${current-1}" ${current===1?'disabled':''} aria-label="Página anterior">←</button>${pages.join('')}<button class="page-btn" data-pagination="${kind}" data-number="${current+1}" ${current===total?'disabled':''} aria-label="Próxima página">→</button></div>`;}
function resultsTable(list, limit=12){const pages=Math.max(1,Math.ceil(list.length/limit));state.casePage=Math.min(state.casePage,pages);const start=(state.casePage-1)*limit,visible=list.slice(start,start+limit);return `${list.length?`<div class="table-wrap"><table class="results-table"><thead><tr><th>Caso / variação</th><th>Camada</th><th>Resultado</th><th>Registro</th><th>Detalhe</th></tr></thead><tbody>${visible.map(c=>`<tr class="row-link" data-case="${esc(c.id)}" tabindex="0" role="button" aria-label="Ver ${esc(c.id)}"><td><span class="case-name">${esc(c.id)}</span><span class="case-objective">${esc(caseDescription(c))}</span><span class="case-desc">${esc(c.input)}</span></td><td>${badge(c.layer,'blue')}</td><td>${statusBadge(rawStatus(c))}${caseBugs(c).map(b=>`<span class="case-desc" style="color:var(--red)">${esc(b)}</span>`).join('')}</td><td style="white-space:nowrap;color:var(--muted)">${esc(c.date)}</td><td>${icon('arrow')}</td></tr>`).join('')}</tbody></table></div>`:empty()}<div class="table-bottom"><span>${list.length?`${start+1}–${Math.min(start+limit,list.length)} de ${list.length} casos`:'0 casos'}</span>${pagination(state.casePage,pages,'cases')}</div>`;}
function resultFilters(){return `<div class="toolbar"><label class="search-field"><span class="sr-only" hidden>Buscar cenário</span>${icon('search')}<input id="case-search" aria-label="Buscar cenário" type="search" placeholder="Buscar CT, cupom, produto ou bug…" value="${esc(state.caseSearch)}"></label><select id="layer-filter" aria-label="Filtrar camada">${selectOptions([['','Todas as camadas'],['UI','Interface · UI'],['API','API']],state.layer)}</select><select id="status-filter" aria-label="Filtrar resultado">${selectOptions([['','Todos os resultados'],['Aprovado','Aprovados'],['Reprovado','Reprovados']],state.status)}</select><select id="group-filter" aria-label="Filtrar grupo">${selectOptions([['','Todos os grupos'],...state.data.groups.map(g=>[g.id,g.id])],state.group)}</select><select id="criterion-filter" aria-label="Filtrar critério">${selectOptions([['','Todos os critérios'],...Array.from({length:11},(_,i)=>{const id='CA'+String(i+1).padStart(2,'0');return[id,id];})],state.criterion)}</select><button class="text-button" data-clear-filters>Limpar</button></div>`;}
function groupsView(){return `<div class="groups-grid">${state.data.groups.map(g=>{const items=dataCases().filter(c=>(c.group||groupOf(c.id))===g.id),failed=items.filter(c=>rawStatus(c)==='Reprovado').length;return `<button class="group-card" data-group="${esc(g.id)}"><header><code>${esc(g.id)}</code>${badge(failed?failed+' reprovados':'Verificado',failed?'red':'green')}</header><p>${esc(g.objective||g.title)}</p><small>${items.length} variações · ${esc(criteriaArray(g.criteria).join(', ')||'Contrato da API / checkout')}</small></button>`;}).join('')}</div>`;}
function criteriaView(){const items=state.data.criteria||[];return `<div class="criteria-grid">${items.map(item=>{const id=item.id,failed=['CA06','CA10'].includes(id),related=id==='CA08';return `<article class="criterion"><header><strong>${esc(id)}</strong>${badge(failed?'Falha confirmada':related?'BUG-001':'Verificado',failed?'red':related?'amber':'green')}</header><p>${esc(item.description)}</p><button class="text-button" data-criterion="${esc(id)}">Ver casos ${icon('arrow')}</button></article>`;}).join('')}</div>`;}
function casesPage(){return heading('Cenários e resultados','',`<button class="button compact" data-failed>Ver ${state.data.summary.failed} reprovações</button>`)+`<div class="tabs" role="tablist" aria-label="Visualização dos cenários">${[['results',state.data.summary.totalCases+' resultados'],['groups',state.data.groups.length+' grupos'],['criteria','11 critérios']].map(([id,label])=>`<button role="tab" aria-selected="${state.caseTab===id}" class="tab-button ${state.caseTab===id?'active':''}" data-case-tab="${id}">${label}</button>`).join('')}</div>`+(state.caseTab==='results'?resultFilters()+`<div class="table-count"><span id="result-count"></span></div><div id="results-table"></div>`:state.caseTab==='groups'?groupsView():criteriaView());}
function updateResults(){const list=casesFiltered();$('#result-count').textContent=`${list.length} de ${dataCases().length} casos`;$('#results-table').innerHTML=resultsTable(list);}
function casePackage(id){return id==='EXP-01'?state.data.explorationEvidence:state.data.caseEvidence.find(e=>e.caseId===id);}
function evidenceFiltered(){return dataCases().filter(c=>(!state.evidenceGroup||(c.group||groupOf(c.id))===state.evidenceGroup)&&(!state.evidenceSearch||norm([c.id,caseDescription(c),c.input,groupById(c.group||groupOf(c.id))?.objective,...caseBugs(c)].join(' ')).includes(norm(state.evidenceSearch))));}
function evidenceCards(){
 const list=evidenceFiltered(),limit=12,pages=Math.max(1,Math.ceil(list.length/limit));state.evidencePage=Math.min(state.evidencePage,pages);const start=(state.evidencePage-1)*limit;
 const cards=list.slice(start,start+limit).map(c=>{const ev=c.evidence||casePackage(c.id),pair=ev?.pairs?.[0];const paths=pair?.mode==='montage'?[pair.montagePath]:pair?[pair.beforePath,pair.afterPath]:ev?.images?.slice(0,1).map(i=>i.path)||[];
  return `<button class="evidence-card scoped-case-card" data-case="${esc(c.id)}" data-case-view="evidence"><div class="preview-pair ${paths.length<2?'single':''}">${paths.length?paths.map(path=>`<img loading="lazy" src="${fileURL(path)}" alt="${esc(c.id)} · evidência">`).join(''):`<div class="api-preview">${icon('code')}<strong>${esc(c.method||'API')}</strong><span>${esc(c.path||'')}</span><b>HTTP ${esc(c.httpStatus||'')}</b></div>`}<span class="preview-label">${c.layer==='API'?'REQUISIÇÃO / RESPOSTA':pair?.mode==='montage'?'MONTAGEM':'ANTES / DEPOIS'}</span></div><div class="evidence-info"><header><code>${esc(c.id)}</code>${statusBadge(rawStatus(c))}</header><h3>${esc(caseDescription(c))}</h3><p class="case-card-data">${esc(c.input)}</p><p>${c.layer==='API'?'1 registro de API':(ev?.images?.length||0)+' '+(ev?.images?.length===1?'captura':'capturas')} · ${esc(c.date)}</p></div></button>`;
 }).join('');
 return `${list.length?`<div class="evidence-grid">${cards}</div>`:empty()}<div class="table-bottom"><span>${list.length?`${start+1}–${Math.min(start+limit,list.length)} de ${list.length} casos`:'0 casos'}</span>${pagination(state.evidencePage,pages,'evidence')}</div>`;
}
function evidencePage(){
 const selected=groupById(state.evidenceGroup),listing=selected||state.evidenceSearch;
 return heading('Evidências')+`<div class="toolbar"><label class="search-field">${icon('search')}<input id="evidence-search" aria-label="Buscar evidência" type="search" placeholder="Buscar caso…" value="${esc(state.evidenceSearch)}"></label><select id="evidence-group-filter" aria-label="Filtrar evidência por cenário">${selectOptions([['','Todos os cenários'],...state.data.groups.map(g=>[g.id,g.id])],state.evidenceGroup)}</select><button class="text-button" data-evidence-reset ${listing?'':'hidden'}>Ver cenários</button></div><div id="evidence-cards">${listing?`${selected?`<div class="evidence-group-bar"><strong>${esc(selected.id)}</strong><span>${esc(groupTitles[selected.id]||selected.objective)}</span></div>`:''}${evidenceCards()}`:evidenceHome()}</div>`;
}
function evidenceHome(){return `<div class="groups-grid">${state.data.groups.map(g=>{const cases=dataCases().filter(c=>c.group===g.id),n=cases.filter(c=>rawStatus(c)==='Reprovado').length;return `<button class="group-card" data-evidence-group="${esc(g.id)}"><header><code>${esc(g.id)}</code>${n?badge(n+' '+(n===1?'reprovado':'reprovados'),'red'):badge('Aprovado','green')}</header><p>${esc(groupTitles[g.id]||g.objective)}</p><small>${cases.length} ${cases.length===1?'caso':'casos'} · ${cases.filter(c=>c.layer==='UI').length} UI · ${cases.filter(c=>c.layer==='API').length} API</small></button>`;}).join('')}</div><div class="explore-callout"><div><strong>EXP-01 · Sessão exploratória</strong><span>1 min 41 s · sem novos bugs</span></div><button class="button compact" data-exploration>Ver evidências</button></div>`;}
function bugsPage(){const affected=dataCases().filter(c=>rawStatus(c)==='Reprovado');return heading('Bugs encontrados')+`<div class="bug-list">${bugRows()}</div><details class="affected-cases"><summary><strong>Casos afetados</strong><span>${affected.length} casos</span></summary><div class="affected-cases-content">${resultsTable(affected,10)}<button class="text-button" data-failed>Ver nos cenários ${icon('arrow')}</button></div></details>`;}
function resolveFile(relative,base){const parts=base.split('/');parts.pop();for(const p of relative.split('/')){if(p==='..')parts.pop();else if(p&&p!=='.')parts.push(p);}return parts.join('/');}
function inline(text,path){
 const rx=/(!?\[([^\]]*)\]\(([^)]+)\)|`([^`]+)`|\*\*([^*]+)\*\*)/g;let out='',position=0,m;
 while((m=rx.exec(text))){out+=esc(text.slice(position,m.index));const raw=m[0];if(m[4]!==undefined)out+=`<code>${esc(m[4])}</code>`;else if(m[5]!==undefined)out+=`<strong>${esc(m[5])}</strong>`;else{const target=m[3],label=m[2];if(/^https?:\/\//.test(target))out+=`<a href="${esc(target)}" target="_blank" rel="noopener noreferrer">${esc(label)}</a>`;else{const [file,anchor]=target.split('#');const resolved=file?resolveFile(file,path):path;if(resolved==='docs/gherkin')out+=`<button class="link" data-doc="docs/gherkin/carrinho.feature">${esc(label)}</button>`;else if(resolved==='evidencias')out+=`<button class="link" data-page="evidence">${esc(label)}</button>`;else if(resolved==='tests')out+=`<button class="link" data-doc="${esc(state.data.summary.automation.files[0]||'playwright.config.ts')}">${esc(label)}</button>`;else if(raw.startsWith('!'))out+=`<img loading="lazy" src="${fileURL(resolved)}" alt="${esc(label)}" data-image="${esc(resolved)}">`;else if(docByPath(resolved))out+=`<button class="link" data-doc="${esc(resolved)}" ${anchor?`data-anchor="${esc(anchor)}"`:''}>${esc(label)}</button>`;else if(/\.(png|jpe?g|webp)$/i.test(resolved))out+=`<button class="link" data-image="${esc(resolved)}">${esc(label)}</button>`;else out+=`<a href="${fileURL(resolved)}" target="_blank" rel="noopener">${esc(label)}</a>`;}}position=rx.lastIndex;}
 return out+esc(text.slice(position));
}
function md(text,path){const lines=String(text).split(/\r?\n/);let html='',i=0;const cells=line=>line.replace(/^\|/,'').replace(/\|$/,'').split(/(?<!\\)\|/).map(s=>s.trim().replace(/\\\|/g,'|'));while(i<lines.length){let line=lines[i];if(!line.trim()){i++;continue;}if(/^```/.test(line)){const code=[];i++;while(i<lines.length&&!/^```/.test(lines[i]))code.push(lines[i++]);i++;html+=`<pre><code>${esc(code.join('\n'))}</code></pre>`;continue;}
 if(line.startsWith('<details>')){html+='<details>';i++;continue;}if(line.startsWith('</details>')){html+='</details>';i++;continue;}if(line.startsWith('<summary>')){html+='<summary>'+esc(line.replace(/<\/?summary>/g,''))+'</summary>';i++;continue;}
 line=line.replace(/<a id="([^"]+)"><\/a>/g,(_,id)=>'');if(!line.trim()){i++;continue;}
 const h=line.match(/^(#{1,6}) (.+)$/);if(h){const id=h[2].toLowerCase().replace(/[^\p{L}\p{N}_\- ]/gu,'').replace(/ /g,'-');html+=`<h${h[1].length} id="doc-${esc(id)}">${inline(h[2],path)}</h${h[1].length}>`;i++;continue;}
 if(line.startsWith('|')&&lines[i+1]?.match(/^\|[ \-:|]+\|?$/)){const heads=cells(line);i+=2;let rows='';while(i<lines.length&&lines[i].startsWith('|'))rows+='<tr>'+cells(lines[i++]).map(c=>'<td>'+inline(c.replace(/<a id="[^"]+"><\/a>/g,''),path)+'</td>').join('')+'</tr>';html+='<table><thead><tr>'+heads.map(c=>'<th>'+inline(c,path)+'</th>').join('')+'</tr></thead><tbody>'+rows+'</tbody></table>';continue;}
 if(/^[-*] /.test(line)){html+='<ul>';while(i<lines.length&&/^[-*] /.test(lines[i])){const item=lines[i++].slice(2),check=item.match(/^\[([ xX])\] (.+)$/);html+='<li>'+ (check?`<span style="color:${check[1]===' '?'var(--muted)':'var(--green)'}">${check[1]===' '?'☐':'☑'}</span> ${inline(check[2],path)}`:inline(item,path))+'</li>';}html+='</ul>';continue;}
 if(/^\d+\. /.test(line)){html+='<ol>';while(i<lines.length&&/^\d+\. /.test(lines[i]))html+='<li>'+inline(lines[i++].replace(/^\d+\. /,''),path)+'</li>';html+='</ol>';continue;}
 html+='<p>'+inline(line,path)+'</p>';i++;}return html;}
function documentsPage(){const documentItem=docByPath(state.docPath)||state.data.documents[0];if(!documentItem)return empty('Documentos indisponíveis','Confira o registro de erros no painel.');state.docPath=documentItem.path;const primary=state.data.documents.filter(d=>/\.(md|feature)$/.test(d.path)),others=state.data.documents.filter(d=>!primary.includes(d));return heading('Documentos')+`<div class="document-layout"><aside class="document-list" aria-label="Arquivos"><span class="eyebrow">DOCUMENTAÇÃO</span>${primary.map(d=>docButton(d)).join('')}<span class="eyebrow">DADOS E CONFIGURAÇÃO</span>${others.map(d=>docButton(d)).join('')}</aside><article class="document-paper"><div class="document-top"><div><strong>${esc(docTitle(documentItem))}</strong><small>${esc(documentItem.path)}</small></div><div style="display:flex;gap:7px"><button class="button compact" data-source-toggle>${state.source?'Leitura':'Ver fonte'}</button><a class="button compact" href="${fileURL(documentItem.path)}" target="_blank" rel="noopener">Original ${icon('external')}</a></div></div><div class="document-content ${documentItem.path.endsWith('.md')&&!state.source?'markdown':''}" id="document-content">${documentItem.path.endsWith('.md')&&!state.source?md(documentItem.content,documentItem.path):`<pre class="source"><code>${esc(formatSource(documentItem.content,documentItem.path))}</code></pre>`}</div></article></div>`;}
function docButton(d){return `<button class="doc-button ${d.path===state.docPath?'active':''}" data-doc="${esc(d.path)}">${icon(d.path.endsWith('.feature')?'code':'file')}<span>${esc(docTitle(d))}<small>${esc(d.path)}</small></span></button>`;}
function formatSource(source,path){if(path.endsWith('.json'))try{return JSON.stringify(JSON.parse(source),null,2);}catch{}return source||'(Arquivo vazio)';}
function renderEvidenceListing(){const box=$('#evidence-cards'),selected=groupById(state.evidenceGroup);if(box)box.innerHTML=selected||state.evidenceSearch?`${selected?`<div class="evidence-group-bar"><strong>${esc(selected.id)}</strong><span>${esc(groupTitles[selected.id]||selected.objective)}</span></div>`:''}${evidenceCards()}`:evidenceHome();const reset=$('[data-evidence-reset]');if(reset)reset.hidden=!selected&&!state.evidenceSearch;}
function render(){if(!state.data)return;$('.nav-button.active')?.classList.remove('active');$(`.nav-button[data-page="${state.page}"]`)?.classList.add('active');for(const b of document.querySelectorAll('.nav-button')){if(b.dataset.page===state.page)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');}$('#breadcrumb').textContent=pageTitles[state.page];document.title=pageTitles[state.page]+' · QA Verzel';$('#main').innerHTML=({overview,cases:casesPage,automation:automationPage,evidence:evidencePage,bugs:bugsPage,documents:documentsPage}[state.page]||overview)();if(state.page==='cases'&&state.caseTab==='results')updateResults();}
function navigate(page){state.page=page;history.replaceState(null,'','#'+page);render();window.scrollTo({top:0,behavior:'instant'});}
function modal(title,eyebrow,html){$('#dialog-title').textContent=title;$('#dialog-eyebrow').textContent=eyebrow;$('#dialog-body').innerHTML=html;const d=$('#detail-dialog');if(!d.open)d.showModal();d.scrollTop=0;}
function caseImage(path,label,scope){const ev=imagePackage(scope),item=ev?.images.find(i=>i.path===path);return `<figure class="evidence-frame"><figcaption>${esc(label)}<span>Ampliar ↗</span></figcaption><button class="compare-image" data-image="${esc(path)}" data-image-scope="${esc(scope)}" aria-label="Ampliar ${esc(label)}"><img loading="lazy" src="${fileURL(path)}" alt="${esc(item?.stage||label)}"></button></figure>`;}
function scopedEvidenceHTML(ev){
 if(!ev)return empty('Evidência indisponível');
 const c=dataCases().find(c=>c.id===ev.caseId),record=ev.records[0];
 if(ev.layer==='API')return `<div class="api-request-bar"><span class="badge blue">${esc(record.method)}</span><code>${esc(record.path)}</code>${badge('HTTP '+record.httpStatus,record.httpStatus>=400?'amber':'green')}</div><div class="api-payloads"><section><h3>Requisição</h3><pre class="source"><code>${record.request==null?'Sem corpo':esc(typeof record.request==='string'?record.request:JSON.stringify(record.request,null,2))}</code></pre></section><section><h3>Resposta</h3><pre class="source"><code>${esc(JSON.stringify(record.response,null,2))}</code></pre></section></div><a class="button compact" href="${fileURL(ev.recordPath)}" download="${esc(ev.caseId)}.json">${icon('file')}Registro deste caso</a>`;
 const pair=ev.pairs[state.comparisonIndex]||ev.pairs[0];let compare='';
 if(pair?.mode==='montage')compare=`<div class="case-evidence-grid montage">${caseImage(pair.montagePath,'Antes e depois',ev.caseId)}</div>`;
 else if(pair)compare=`<div class="case-evidence-grid">${caseImage(pair.beforePath,'Antes',ev.caseId)}${caseImage(pair.afterPath,'Depois',ev.caseId)}</div>`;
 else if(ev.images.length)compare=caseImage(ev.images[0].path,'Captura',ev.caseId);
 const pairSelect=ev.pairs.length>1?`<label class="comparison-selector">Etapa <select id="comparison-selector" aria-label="Selecionar comparativo">${ev.pairs.map((p,i)=>`<option value="${i}" ${state.comparisonIndex===i?'selected':''}>${esc(p.label)}</option>`).join('')}</select></label>`:'';
 return `<div class="evidence-actions"><span>${ev.images.length} ${ev.images.length===1?'captura':'capturas'}</span><a class="button compact" href="${fileURL(ev.recordPath)}" download="${esc(ev.caseId)}.json">${icon('file')}Registro deste caso</a></div>${pairSelect}${compare}<div class="case-thumbnails">${ev.images.map((f,i)=>`<button class="case-thumbnail" data-image="${esc(f.path)}" data-image-scope="${esc(ev.caseId)}" aria-label="Etapa ${i+1}: ${esc(f.stage)}"><img loading="lazy" src="${fileURL(f.path)}" alt=""><span>${i+1}. ${esc(f.stage)}</span></button>`).join('')}</div><details class="evidence-timeline"><summary>Etapas e horários</summary><div class="stage-list">${ev.images.map((f,i)=>`<div class="stage-item"><span>${i+1}. ${esc(f.stage)}<small>${esc(dateText(f.time))}</small></span><button class="link" data-image="${esc(f.path)}" data-image-scope="${esc(ev.caseId)}">Ampliar</button></div>`).join('')}</div></details>`;
}
function moneyValues(text){const numbers=String(text||'').match(/\d+,\d{2}/g)||[];return numbers.length>=4?numbers.slice(0,4):null;}
function resultHTML(c){
 const expected=moneyValues(c.expected),actual=moneyValues(c.actual);
 const comparison=expected&&actual?`<table class="money-table"><thead><tr><th>Valor</th><th>Esperado</th><th>Obtido</th></tr></thead><tbody>${['Subtotal','Desconto','Frete','Total'].map((label,i)=>`<tr class="${expected[i]!==actual[i]?'money-fail':''}"><th>${label}</th><td>R$ ${expected[i]}</td><td>R$ ${actual[i]}</td></tr>`).join('')}</tbody></table>`:`<div class="comparison"><div class="comparison-box"><span class="eyebrow">Esperado</span><p>${esc(c.expected)}</p></div><div class="comparison-box ${rawStatus(c)==='Reprovado'?'fail':''}"><span class="eyebrow">Obtido</span><p>${esc(c.actual)}</p></div></div>`;
 return `<div class="case-input"><h3>Dados</h3><p style="white-space:pre-wrap">${esc(c.input)}</p>${c.dados?`<details><summary>Dados completos</summary><pre class="source"><code>${esc(JSON.stringify(c.dados,null,2))}</code></pre></details>`:''}</div>${comparison}`;
}
function scenarioSpecifications(c){
 const files=groupById(c.group)?.features||[],specs=[];
 const variations={'CT-006-UI-com-cupom':'com_cupom','CT-006-UI-sem-cupom':'sem_cupom','CT-002-minusculas':'minusculas','CT-002-letras_mistas':'letras_mistas','CT-002-espacos_inicio':'espacos_inicio','CT-002-espacos_fim':'espacos_fim','CT-002-letras_e_espacos':'letras_e_espacos','CT-013-UI-nome-sem-sobrenome':'Nome sem sobrenome','CT-013-UI-email-sem-arroba':'E-mail sem arroba','CT-013-UI-cep-sete-digitos':'CEP com 7 dígitos','CT-013-UI-cep-nove-digitos':'CEP com 9 dígitos','CT-013-UI-nome-vazio':'Nome vazio','CT-013-UI-email-vazio':'E-mail vazio','CT-013-UI-cep-vazio':'CEP vazio'};
 const trailingTags=text=>text.replace(/(?:^|\r?\n)[ \t]*@[^\r\n]*(?:\r?\n[ \t]*@[^\r\n]*)*[ \t\r\n]*$/,'').trimEnd();
 const tagsBefore=(source,index)=>{const lines=source.slice(0,index).split(/\r?\n/);let n=lines.length-1;while(n>=0&&!lines[n].trim())n--;const tags=[];while(n>=0&&/^\s*@/.test(lines[n]))tags.unshift(lines[n--].trim());return tags;};
 for(const file of files){if(c.layer==='API'&&!file.endsWith('/api.feature'))continue;if(c.layer==='UI'&&file.endsWith('/api.feature'))continue;
  const doc=docByPath(file);if(!doc)continue;const source=doc.content,starts=[...source.matchAll(/^  (?:Cenário|Esquema do Cenário):.+$/gm)];
  for(let i=0;i<starts.length;i++){const begin=starts[i].index,tags=tagsBefore(source,begin);
   let block=trailingTags(source.slice(begin,i+1<starts.length?starts[i+1].index:source.length));const title=starts[i][0];let match=false;
   const exampleStarts=[...block.matchAll(/^[ \t]*Exemplos:[^\r\n]*$/gm)],selected=variations[c.id]||c.id;let example=null;
   for(let n=0;n<exampleStarts.length;n++){const start=exampleStarts[n],segment=trailingTags(block.slice(start.index,exampleStarts[n+1]?.index??block.length)),rows=segment.split(/\r?\n/).filter(line=>/^\s*\|/.test(line));
    const row=rows.slice(1).find(line=>line.trim().split('|')[1]?.trim()===selected);
    if(row){example={tags:tagsBefore(block,start.index),title:start[0].trim(),header:rows[0],row};break;}
   }
   if(c.layer==='API'){
    match=Boolean(example);
    if(c.id==='CT-013-API-tres-campos')match=/todos os campos inválidos/.test(title);
    if(c.id.startsWith('CT-014'))match=c.id.endsWith('catalogo')?/catálogo/.test(title):c.id.endsWith('P005')?/produto existente/.test(title):/produto inexistente/.test(title);
    if(c.id.startsWith('CT-016'))match=c.id.includes('json')?/JSON sintaticamente/.test(title):c.id.includes('rota')?/rota da API inexistente/.test(title):/método não permitido/.test(title);
   }else if(tags.some(line=>line.split(/\s+/).includes('@'+c.group))){
    match=!exampleStarts.length||Boolean(example);
    if(c.group==='CT-007')match=c.id.includes('jaqueta')?/acima de duzentos/.test(title):/desconto reduz/.test(title);
    if(c.group==='CT-010')match=c.id.includes('aumentar')?/ao aumentar/.test(title):c.id.includes('diminuir')?/ao diminuir/.test(title):/adicionar e remover/.test(title);
   }
   if(!match)continue;
   if(example){const body=trailingTags(block.slice(0,exampleStarts[0].index));block=body+'\n\n'+example.tags.map(tag=>'    '+tag+'\n').join('')+'    '+example.title+'\n'+example.header+'\n'+example.row;}
   specs.push({path:file,text:'# language: pt\n'+(tags.length?tags.join('\n')+'\n':'')+block.trim()});
  }
 }
 return specs;
}
function renderCaseDetail(){
 const c=dataCases().find(c=>c.id===state.activeCase);if(!c)return;
 const ev=c.evidence||casePackage(c.id),group=groupById(c.group);
 const tabs=[['result','Resultado'],['evidence',c.layer==='API'?'API':'Evidências'],['gherkin','Gherkin']];
 const content=state.detailTab==='result'?resultHTML(c):state.detailTab==='evidence'?scopedEvidenceHTML(ev):scenarioSpecifications(c).map(spec=>`<section class="gherkin-case"><pre class="source"><code>${esc(spec.text)}</code></pre><button class="text-button" data-doc="${esc(spec.path)}">Arquivo Gherkin ${icon('external')}</button></section>`).join('')||empty('Especificação disponível nos documentos');
 const bugActions=caseBugs(c).map(id=>`<button class="button case-bug-action" data-bug="${esc(id)}">${icon('bug')}Ver ${esc(id)} ${icon('arrow')}</button>`).join('');
 modal(c.id,groupTitles[c.group]||group?.objective||'',`<div class="case-summary-bar">${statusBadge(rawStatus(c))}${badge(c.layer,'blue')}<span>${esc(c.date)}</span>${bugActions?`<div class="case-bug-actions" aria-label="Bugs encontrados neste caso">${bugActions}</div>`:''}</div><section class="case-objective-block" aria-label="Objetivo do cenário"><h3>Objetivo</h3><p>${esc(caseDescription(c))}</p></section><div class="details-tabs" role="tablist" aria-label="Detalhes do caso">${tabs.map(([id,label])=>`<button class="detail-tab ${state.detailTab===id?'active':''}" role="tab" aria-selected="${state.detailTab===id}" data-detail-tab="${id}">${label}</button>`).join('')}</div><div class="case-context">${content}</div>`);
}
function openCase(id,tab='result'){state.activeAutomation=null;state.activeCase=id;state.detailTab=tab;state.comparisonIndex=0;renderCaseDetail();}
function openEvidence(id){if(id==='EV-036')return openExploration();const cases=dataCases().filter(c=>c.evidenceId===id);if(cases.length===1)return openCase(cases[0].id,'evidence');state.evidenceGroup=cases[0]?.group||'';state.evidenceSearch='';navigate('evidence');}
function openExploration(){state.activeCase=null;state.comparisonIndex=0;const ev=casePackage('EXP-01');modal('EXP-01','Sessão exploratória',`<div class="case-summary-bar">${badge('1 min 41 s','blue')}${badge('Sem novos bugs','green')}</div>${scopedEvidenceHTML(ev)}`);}
function openBug(id){const b=state.data.bugs.find(b=>b.id===id);if(!b)return;state.activeCase=null;const list=dataCases().filter(c=>caseBugs(c).includes(id));modal(b.title,id,`<div class="case-summary-bar">${badge('Severidade '+b.severity,b.severity==='Alta'?'red':'amber')}${badge('Prioridade '+b.priority)}${badge(list.length+' casos','red')}</div><div class="markdown">${md(b.markdown,'docs/bugs.md')}</div><div class="detail-section"><h3>Casos afetados</h3><div class="case-bug-links">${list.map(c=>`<button class="button compact" data-case="${esc(c.id)}">${esc(c.id)}</button>`).join('')}</div></div>`);}
function openImage(path,scope){
 const ev=scope?imagePackage(scope):null,paths=ev?ev.images.map(i=>i.path):[path];
 if(!paths.includes(path))return toast('Captura fora deste caso.');
 state.imageScope=ev?.caseId||null;state.imagePaths=[...new Set(paths)];state.imageIndex=state.imagePaths.indexOf(path);state.imageFit=true;if(!$('#image-dialog').open)$('#image-dialog').showModal();refreshImage();
}
function refreshImage(){const path=state.imagePaths[state.imageIndex],ev=state.imageScope?imagePackage(state.imageScope):null,capture=ev?.images.find(i=>i.path===path)||captures().find(i=>i.path===path);$('#image-title').textContent=(state.imageScope?state.imageScope+' · ':'')+(capture?.stage||path.split('/').pop());$('#large-image').src=fileURL(path);$('#large-image').alt=capture?.stage||path.split('/').pop();$('#image-position').textContent=`${state.imageIndex+1} / ${state.imagePaths.length}`;$('#image-original').href=fileURL(path);$('#previous-image').disabled=state.imageIndex===0;$('#next-image').disabled=state.imageIndex===state.imagePaths.length-1;$('.image-stage').scrollTop=0;$('.image-stage').scrollLeft=0;if($('#large-image').complete&&$('#large-image').naturalWidth)updateImageSize();}
function applyImageZoom(){const img=$('#large-image');if(!img.naturalWidth)return;img.style.width=img.naturalWidth*state.imageZoom/100+'px';img.style.height=img.naturalHeight*state.imageZoom/100+'px';$('#image-zoom').value=state.imageZoom;$('#image-zoom-value').textContent=state.imageZoom+'%';}
function fitImage(){const img=$('#large-image'),stage=$('.image-stage'),canvasStyle=getComputedStyle($('.image-canvas'));if(!img.naturalWidth||!stage.clientWidth||!stage.clientHeight)return;const width=stage.clientWidth-parseFloat(canvasStyle.paddingLeft)-parseFloat(canvasStyle.paddingRight),height=stage.clientHeight-parseFloat(canvasStyle.paddingTop)-parseFloat(canvasStyle.paddingBottom);state.imageFit=true;state.imageZoom=Math.max(1,Math.min(200,Math.floor(Math.min(width/img.naturalWidth,height/img.naturalHeight,1)*100)));applyImageZoom();stage.scrollLeft=0;stage.scrollTop=0;}
function updateImageSize(){if(state.imageFit)fitImage();else applyImageZoom();}
function openDoc(path,anchor){state.activeCase=null;$('#detail-dialog').close();state.docPath=path;state.source=false;navigate('documents');if(anchor)requestAnimationFrame(()=>document.getElementById('doc-'+anchor)?.scrollIntoView({block:'start'}));}
document.addEventListener('click',e=>{
 const node=e.target.closest('[data-page],[data-case],[data-bug],[data-evidence],[data-image],[data-doc],[data-group],[data-criterion],[data-case-tab],[data-evidence-tab],[data-failed],[data-clear-filters],[data-pagination],[data-source-toggle],[data-detail-tab],[data-evidence-group],[data-evidence-reset],[data-exploration],[data-automation],[data-automation-tab],[data-automation-ct],[data-automation-clear]');if(!node||!state.data)return;
 if(node.dataset.automation){openAutomation(node.dataset.automation);return;}
 if(node.dataset.automationTab){state.automationTab=node.dataset.automationTab;renderAutomationDetail();return;}
 if(node.hasAttribute('data-automation-clear')){state.automationSearch='';state.automationLayer='';state.automationStatus='';render();return;}
 if(node.dataset.automationCt){const id=node.dataset.automationCt;state.activeAutomation=null;if(dataCases().some(c=>c.id===id)){openCase(id);return;}$('#detail-dialog').close();state.caseTab='results';state.group=groupOf(id);state.caseSearch='';state.status='';state.layer='';state.criterion='';state.casePage=1;navigate('cases');return;}
 if(node.dataset.detailTab){state.detailTab=node.dataset.detailTab;state.comparisonIndex=0;renderCaseDetail();return;}if(node.dataset.evidenceGroup){state.evidenceGroup=node.dataset.evidenceGroup;state.evidenceSearch='';state.evidencePage=1;render();return;}if(node.hasAttribute('data-evidence-reset')){state.evidenceGroup='';state.evidenceSearch='';state.evidencePage=1;render();return;}if(node.hasAttribute('data-exploration')){openExploration();return;}if(node.dataset.page){navigate(node.dataset.page);return;}if(node.dataset.case){openCase(node.dataset.case,node.dataset.caseView||'result');return;}if(node.dataset.bug){openBug(node.dataset.bug);return;}if(node.dataset.evidence){openEvidence(node.dataset.evidence);return;}if(node.dataset.image){openImage(node.dataset.image,node.dataset.imageScope);return;}if(node.dataset.doc){openDoc(node.dataset.doc,node.dataset.anchor);return;}
 if(node.dataset.group){state.caseTab='results';state.group=node.dataset.group;state.caseSearch='';state.status='';state.layer='';state.criterion='';state.casePage=1;navigate('cases');return;}
 if(node.dataset.criterion){state.caseTab='results';state.criterion=node.dataset.criterion;state.group='';state.status='';state.layer='';state.caseSearch='';state.casePage=1;render();return;}
 if(node.dataset.caseTab){state.caseTab=node.dataset.caseTab;render();return;}if(node.dataset.evidenceTab){state.evidenceTab=node.dataset.evidenceTab;state.evidencePage=1;render();return;}
 if(node.hasAttribute('data-failed')){state.caseTab='results';state.status='Reprovado';state.group='';state.layer='';state.caseSearch='';state.criterion='';state.casePage=1;navigate('cases');return;}
 if(node.hasAttribute('data-clear-filters')){state.caseSearch='';state.layer='';state.status='';state.group='';state.criterion='';state.casePage=1;render();return;}
 if(node.dataset.pagination){if(node.dataset.pagination==='cases'){state.casePage=Number(node.dataset.number);if(state.page==='cases')updateResults();else render();}else{state.evidencePage=Number(node.dataset.number);$('#evidence-cards').innerHTML=evidenceCards();}return;}
 if(node.hasAttribute('data-source-toggle')){state.source=!state.source;render();return;}
});
document.addEventListener('input',e=>{if(e.target.id==='case-search'){state.caseSearch=e.target.value;state.casePage=1;updateResults();}if(e.target.id==='evidence-search'){state.evidenceSearch=e.target.value;state.evidencePage=1;renderEvidenceListing();}if(e.target.id==='automation-search'){state.automationSearch=e.target.value;updateAutomationResults();}});
document.addEventListener('change',e=>{if(e.target.id==='comparison-selector'){state.comparisonIndex=Number(e.target.value);if(state.activeCase)renderCaseDetail();else{const ev=casePackage('EXP-01');$('#dialog-body').innerHTML=scopedEvidenceHTML(ev);}return;}const map={'layer-filter':'layer','status-filter':'status','group-filter':'group','criterion-filter':'criterion'};if(map[e.target.id]){state[map[e.target.id]]=e.target.value;state.casePage=1;updateResults();}if(e.target.id==='evidence-group-filter'){state.evidenceGroup=e.target.value;state.evidencePage=1;renderEvidenceListing();}});
document.addEventListener('change',e=>{if(e.target.id==='automation-layer')state.automationLayer=e.target.value;else if(e.target.id==='automation-status')state.automationStatus=e.target.value;else return;updateAutomationResults();});
document.addEventListener('keydown',e=>{const row=e.target.closest('tr[data-case],tr[data-automation]');if(row&&(e.key==='Enter'||e.key===' ')){e.preventDefault();if(row.dataset.automation)openAutomation(row.dataset.automation);else openCase(row.dataset.case);}if($('#image-dialog').open&&!e.target.closest('input,select,textarea,[contenteditable="true"],.image-stage')&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();state.imageIndex=Math.max(0,Math.min(state.imagePaths.length-1,state.imageIndex+(e.key==='ArrowLeft'?-1:1)));refreshImage();}});
$('#close-dialog').addEventListener('click',()=>$('#detail-dialog').close());$('#close-image').addEventListener('click',()=>$('#image-dialog').close());
for(const dialog of document.querySelectorAll('dialog'))dialog.addEventListener('click',e=>{if(e.target===dialog){const rect=dialog.getBoundingClientRect();if(e.clientX<rect.left||e.clientX>rect.right||e.clientY<rect.top||e.clientY>rect.bottom)dialog.close();}});
$('#previous-image').addEventListener('click',()=>{if(state.imageIndex>0){state.imageIndex--;refreshImage();}});$('#next-image').addEventListener('click',()=>{if(state.imageIndex<state.imagePaths.length-1){state.imageIndex++;refreshImage();}});
$('#image-zoom').addEventListener('input',e=>{state.imageFit=false;state.imageZoom=Number(e.target.value);applyImageZoom();});
$('#fit-image').addEventListener('click',fitImage);
$('#large-image').addEventListener('load',updateImageSize);
window.addEventListener('resize',()=>{if($('#image-dialog').open&&state.imageFit)fitImage();});
async function loadData(notify=false){$('#refresh').disabled=true;try{const response=await fetch('./data.json',{cache:'no-store'});if(!response.ok)throw new Error('Não foi possível ler os registros do projeto.');const data=await response.json();if(!Array.isArray(data.cases)||!data.summary)throw new Error('Os registros estão incompletos.');state.data=data;automationPayloads.clear();$('#nav-cases').textContent=data.cases.length;$('#nav-bugs').textContent=data.bugs.length;$('#nav-automation').textContent=data.automation?.tests?.length||0;render();if(data.errors?.length)toast('Alguns arquivos não puderam ser lidos. Consulte os registros.');else if(notify)toast('Dados atualizados.');}catch(error){$('#main').innerHTML=empty('Não foi possível carregar o projeto',error.message)+`<div style="text-align:center;margin-top:20px"><button class="button" id="retry-load">Tentar novamente</button></div>`;$('#retry-load')?.addEventListener('click',()=>loadData());}finally{$('#refresh').disabled=false;}}
$('#refresh').addEventListener('click',()=>loadData(true));state.page=pageTitles[location.hash.slice(1)]?location.hash.slice(1):'overview';loadData();
